---
title: "COVID-19 EMA/TAR"
author: "David Jackson"
date: "8/10/2020"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(RSQLite)
theme_set(theme_light())
```
```{r}

db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
dbListTables(db)
```
```{r}
DF <-dbGetQuery(db,"select * from ECDC")
DF$Reported <- as.Date(DF$Reported)
ES <- subset(DF,Countries =="USA" & Cases >0)


```
```{r}
source("../TAR/R/hello.R")
```

## Calculate movingAverage and EMA

```{r}
ES$RM <- movingAverage(ES$Cases,7,center=TRUE)
ES$EMA <- myEMA(price=ES$Cases,n=7)
```
```{r}
ggplot(ES) + geom_line(aes(x=Reported,y=Cases,col="Cases")) +
 geom_line(aes(x=Reported,y=RM,col="Rolling")) +
  geom_line(aes(x=Reported,y=EMA,col="EMS")) + 
  labs(title="COVID-19 Cases: Rolling Mean vs EMA")
```
```{r}
ES$RMD <- movingAverage(ES$Deaths,7,center=TRUE)
ES$EMAD <- myEMA(price=ES$Deaths,n=7)
```
```{r}
ggplot(ES) + geom_line(aes(x=Reported,y=Deaths,col="Deaths")) +
  geom_line(aes(x=Reported,y=RMD,col="Rolling")) +
  geom_line(aes(x=Reported,y=EMAD,col="EMS")) + 
  labs(title="COVID-19 Deaths: Rolling Mean vs EMA")
```
```{r}
ggplot(ES) + geom_line(aes(x=Reported,y=Cases,col="Cases")) +
  geom_smooth(aes(x=Reported,y=Cases,col="loess"))
```

```{r}
ggplot(ES) + geom_line(aes(x=Reported,y=Deaths,col="Deaths")) +
  geom_smooth(aes(x=Reported,y=Deaths,col="loess"))
```
